### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by yashkolambekar** [idolcs/idolcs.com#11]
Home page (Not logged in)
![image](https://github.com/idolcs/idolcs.com/assets/41070233/8d658aac-726e-4e25-8d3f-7dd4994f6aa5)

Home page (Logged in)
![image](https://github.com/idolcs/idolcs.com/assets/41070233/ecb156b1-9272-4421-a07f-0f38a97b54ab)

**Comment by akshaymagrani** [comment]
Let me do this.
